services:
  - type: web
    name: optimat-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./run_server.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: SERVER_PORT
        value: 8000
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false 